[package]
name = "unrust-proc-macro"
description = "The unrust proc macro crate."
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true
path = "macro.rs"

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1"